### ISSUE TITLE
webchat messages order

### ISSUE THREAD

**Issue by lodelestra** [Opla/webchat#17]
Opla CE - PREPROD | v0.1.0 - b:ci.766 c:95d2aea d:10.09.18 15:24

On a published Webchat, with messages send very quickly, response appear before message.
It looks like Playground is not affected by this issue.

<img width="599" alt="screen shot 2018-09-24 at 17 09 36" src="https://user-images.githubusercontent.com/10141712/45960739-26107f00-c01d-11e8-9103-dc99677c2adc.png">

from Opla/opla#55

**Comment by mikbry** [comment]
This is fixed in this pull request https://github.com/Opla/webchat/pull/15
But the version on bot.opla.ai is not up to date
